### PR TITLE
Put together a new TLS workflow

### PR DESCRIPTION
**Pull request by whit537**
Picks up from https://github.com/gratipay/gratipay.com/issues/4327.

### Todo

- [x] sort out [renewal](https://certbot.eff.org/docs/using.html#renewing-certificates)
- [x] `grtp.co`
    - [x] challenge
    - [x] cert update
- [x] `assets.gratipay.com`
    - [x] challenge
    - [x] cert update
- [x] `gratipay.com`
    - [x] challenge
    - [x] cert update
- [x] don't forget `www` subdomains!

### CODE REVIEW

**Comment by whit537** [comment]
Looking at [renewal](https://certbot.eff.org/docs/using.html#renewing-certificates) ... do we have to reinstall the cert after renewing it?

**Comment by whit537** [comment]
> We realize that our service is young, and that automation is new to many subscribers, so we chose a lifetime that allows plenty of time for manual renewal if necessary. We recommend that subscribers renew every sixty days. Once automated renewal tools are widely deployed and working well, we may consider even shorter lifetimes.

https://letsencrypt.org/2015/11/09/why-90-days.html

**Comment by whit537** [comment]
For `grtp.co` we are using nginx, so we should be able to use `certbot` directly on the droplet.

For `assets.gratipay.com`, can we put a read-only resource at `/assets/.well-known/acme-challenge/%token.spt`? So for that domain you'd load the challenge using:

https://gratipay.com/.well-known/acme-challenge/foo

And then hit it at:

https://assets.gratipay.com/.well-known/acme-challenge/foo

**Comment by whit537** [comment]
Regarding renewal, it seems that the intention behind Let's Encrypt is for cert rolling to become a fully automated process(!). I guess that means a cron job on grtp.co, and a @gratipay-bot job for gratipay.com and assets.gratipay.com.

**Comment by whit537** [comment]
If we wanna go that far ...

**Comment by whit537** [comment]
... and I'm not sure we do. I like that with Payday for example someone is responsible to think about actively it. I think we want to get it close to a one click process, but still have someone responsible to click the button and babysit the process. Otherwise we run the risk that we'll just totally space it until we find out from users because they're getting cert failures.

**Comment by whit537** [comment]
Though it could work to automate it, but also add it to the payday routine to check in on the cert process.

**Comment by whit537** [comment]
Alright, once https://github.com/gratipay/gratipay.com/pull/4333 is out we should be ready to roll. I think we should go in order of increasing risk:

- `grtp.co`
- `assets.gratipay.com`
- `gratipay.com`

**Comment by whit537** [comment]
First target: `grtp.co`.

**Comment by whit537** [comment]
I am following these instructions:

https://certbot.eff.org/all-instructions/#ubuntu-14-04-trusty-nginx

**Comment by whit537** [comment]
```
root@grtp:~# ./certbot-auto -c ~grtp/production/infra/certbot.ini --nginx
Saving debug log to /root/letsencrypt.log

-------------------------------------------------------------------------------
Please read the Terms of Service at
https://letsencrypt.org/documents/LE-SA-v1.1.1-August-1-2016.pdf. You must agree
in order to register with the ACME server at
https://acme-v01.api.letsencrypt.org/directory
-------------------------------------------------------------------------------
(A)gree/(C)ancel: a

-------------------------------------------------------------------------------
Would you be willing to share your email address with the Electronic Frontier
Foundation, a founding partner of the Let's Encrypt project and the non-profit
organization that develops Certbot? We'd like to send you email about EFF and
our work to encrypt the web, protect its users and defend digital rights.
-------------------------------------------------------------------------------
(Y)es/(N)o: n
Obtaining a new certificate
Performing the following challenges:
None of the preferred challenges are supported by the selected plugin

IMPORTANT NOTES:
 - If you lose your account credentials, you can recover through
   e-mails sent to support@gratipay.com.
 - Your account credentials have been saved in your Certbot
   configuration directory at /root. You should make a secure backup
   of this folder now. This configuration directory will also contain
   certificates and private keys obtained by Certbot so making regular
   backups of this folder is ideal.
root@grtp:~#
```

```ini
config-dir           = .
work-dir             = .
logs-dir             = .
nginx                = 1
preferred-challenges = http
email                = support@gratipay.com
domains              = grtp.co, www.grtp.co, gttp.co, www.gttp.co
rsa-key-size         = 4096
```

**Comment by whit537** [comment]
Still the old cert.

**Comment by clone1018** [comment]
You'll need to reload the webserver

**Comment by whit537** [comment]
Reloaded, still the old cert. I think this line is curious:

> None of the preferred challenges are supported by the selected plugin

**Comment by whit537** [comment]
I suspect that handling confirmation for multiple domains is going to be annoying as well.

**Comment by whit537** [comment]
http://serverfault.com/questions/755662/nginx-disable-htaccess-and-hidden-files-but-allow-well-known-directory

**Comment by whit537** [comment]
Progress?

```
Press Enter to Continue
Waiting for verification...
Cleaning up challenges
Failed authorization procedure. www.gttp.co (http-01): urn:acme:error:connection :: The server could not connect to the client to verify the domain :: DNS problem: NXDOMAIN looking up A for www.gttp.co, www.grtp.co (http-01): urn:acme:error:connection :: The server could not connect to the client to verify the domain :: DNS problem: NXDOMAIN looking up A for www.grtp.co

IMPORTANT NOTES:
 - If you lose your account credentials, you can recover through
   e-mails sent to support@gratipay.com.
 - The following errors were reported by the server:

   Domain: www.gttp.co
   Type:   connection
   Detail: DNS problem: NXDOMAIN looking up A for www.gttp.co

   Domain: www.grtp.co
   Type:   connection
   Detail: DNS problem: NXDOMAIN looking up A for www.grtp.co

   To fix these errors, please make sure that your domain name was
   entered correctly and the DNS A record(s) for that domain
   contain(s) the right IP address. Additionally, please check that
   your computer has a publicly routable IP address and that no
   firewalls are preventing the server from communicating with the
   client. If you're using the webroot plugin, you should also verify
   that you are serving files from the webroot path you provided.
 - Your account credentials have been saved in your Certbot
   configuration directory at /root/cert. You should make a secure
   backup of this folder now. This configuration directory will also
   contain certificates and private keys obtained by Certbot so making
   regular backups of this folder is ideal.
root@grtp:~/cert#
```

```diff
diff --git a/infra/nginx.conf b/infra/nginx.conf
index 4df7585..050bcdd 100644
--- a/infra/nginx.conf
+++ b/infra/nginx.conf
@@ -30,6 +30,10 @@ server {
         autoindex on;
         try_files $uri $uri/ =404;
 
+        location ^~ /.well-known/acme-challenge/ {
+                allow all;
+        }
+
         location ~ /\.  {
                 return 404;
         }
```

**Comment by whit537** [comment]
Well, considering we haven't had `www.*` in DNS for who knows how long, no need to bother with that now, right?

**Comment by whit537** [comment]
💃 

```
-------------------------------------------------------------------------------
Press Enter to Continue
Waiting for verification...
Cleaning up challenges
Generating key (4096 bits): /root/cert/keys/0000_key-certbot.pem
Creating CSR: /root/cert/csr/0000_csr-certbot.pem
Non-standard path(s), might not work with crontab installed by your operating system package manager

IMPORTANT NOTES:
 - Congratulations! Your certificate and chain have been saved at
   /root/cert/live/grtp.co/fullchain.pem. Your cert will expire on
   2017-05-11. To obtain a new or tweaked version of this certificate
   in the future, simply run certbot-auto again. To non-interactively
   renew *all* of your certificates, run "certbot-auto renew"
 - If you like Certbot, please consider supporting our work by:

   Donating to ISRG / Let's Encrypt:   https://letsencrypt.org/donate
   Donating to EFF:                    https://eff.org/donate-le

root@grtp:~/cert#
```

**Comment by whit537** [comment]
Now to install the cert and restart nginx ...

**Comment by whit537** [comment]
BLAM!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! 💃 🌻 

screen shot 2017-02-10 at 2 41 56 pm

**Comment by whit537** [comment]
Alright, I've written up , and {assets,downloads}.gratipay.com is ready to go:

screen shot 2017-02-10 at 4 01 17 pm

**Comment by whit537** [comment]
So now we have to decide where we're going to run `certbot` for `*.gratipay.com`, because it apparently creates an account for us(?) and then we can reuse that subsequently to renew and probably revoke(?), and we don't really want that hanging around on our laptops, do we?

**Comment by whit537** [comment]
But we can also recover that account via email, right?

https://community.letsencrypt.org/t/what-are-accounts-do-i-need-to-backup-them/21318

**Comment by whit537** [comment]
> This is not really true anymore - account recovery via email was planned to be added at some point, but has been removed from the spec since.

But otherwise ...

> Losing your account key (as in data loss, not losing it to an attacker :smile:) would not be the end of the world. You won't be able to change the email address for that particular account, and you won't be able to revoke any certificates if you also lose the private key paired with that certificate, but that's about it.

**Comment by whit537** [comment]
I think that for `*.gratipay.com`, we should run `certbot` locally and then delete Let's Encrypt account info. You cool with that @clone1018 @EdOverflow?

**Comment by whit537** [comment]
If we're agreed on that, then I think we are ready to issue a cert for `{assets,download}.gratipay.com`!

**Comment by clone1018** [comment]
So we have disposable certbot creds?

**Comment by whit537** [comment]
@clone1018 Yes! I guess? I think it means that if we need to revoke a cert we have a hassle. What does that look like?

**Comment by whit537** [comment]
https://crt.sh/?id=89497488

**Comment by whit537** [comment]
https://community.letsencrypt.org/t/how-to-revoke-a-certificate-without-account-key-or-email/22000/9

**Comment by clone1018** [comment]
afaik you can just issue another cert regardless of the existing one

**Comment by whit537** [comment]
I say we go for it. The reason to revoke a certificate would be that the private key was compromised. If we delete the private key locally, then it only exists at Heroku. If someone compromises our Heroku account then we've got bigger problems.

**Comment by clone1018** [comment]
Pull the lever!

**Comment by whit537** [comment]
SIR YES SIR!!!!!!!!

**Comment by whit537** [comment]
Okay, I started in on `assets.gratipay.com`. It seems to be working so far! But `downloads.gratipay.com` is not, because that is a PUSH zone rather than a PULL zone. We would need to upload files to the domain to get that to work. However, do we really need that anymore?

**Comment by whit537** [comment]
> This is not really true anymore

https://github.com/certbot/certbot/pull/4212

**Comment by whit537** [comment]
I do see some traffic for `downloads.gratipay.com`:

screen shot 2017-02-10 at 5 54 25 pm

But I don't remember how to login via ftp (I thought there was an ftp password reset somewhere?) in order to see what files are there. I seem to recall we used that for a Vagrant box file(?), but I don't find mention of that [in the README](https://raw.githubusercontent.com/gratipay/gratipay.com/2048/README.md) as I'd expect.

I *think* this is showing me that we have no files in there:

screen shot 2017-02-10 at 5 53 22 pm

But then what is being downloaded? Is it something to do with our font setup?

**Comment by whit537** [comment]
Yeah, here it is. It's part of how we do fonts.

https://downloads.gratipay.com/fonts/244520/BE1BAD4EE32BF8D39.css

screen shot 2017-02-10 at 5 56 41 pm

**Comment by whit537** [comment]
https://www.maxcdn.com/one/tutorial/reset-push-ftp-password/

**Comment by whit537** [comment]
Yeah, once I login I can see assets in the web UI. Pretty sure I have to use sftp to upload, though.

screen shot 2017-02-10 at 6 06 22 pm

**Comment by whit537** [comment]
Alright, I manually cleared out the `acme_challenges` table since the `downloads.*` challenge was still in there and I had lost the token. Gonna make another go of it here ...

**Comment by whit537** [comment]
Heh, actually, I hadn't lost it. 😊

**Comment by whit537** [comment]
Okay, I've uploaded the file but am still getting a 404. I've confirmed via the web UI that the file is where it should be. My hunch is that we're running afoul of a hidden directory restriction. Overcomeable? 😞

**Comment by whit537** [comment]
Alright, talked to MaxCDN support, and this does not appear to be overcomeable. How about [DNS verification](https://tools.ietf.org/html/draft-ietf-acme-acme-03#section-7.4)?

**Comment by whit537** [comment]
DNS! 💃

```
Once this is deployed,
-------------------------------------------------------------------------------
Press Enter to Continue
Waiting for verification...
Cleaning up challenges
Generating key (4096 bits): /Users/whit537/personal/gratipay/inside.gratipay.com/certs/tmp/keys/0000_key-certbot.pem
Creating CSR: /Users/whit537/personal/gratipay/inside.gratipay.com/certs/tmp/csr/0000_csr-certbot.pem
Non-standard path(s), might not work with crontab installed by your operating system package manager

IMPORTANT NOTES:
 - Congratulations! Your certificate and chain have been saved at
   /Users/whit537/personal/gratipay/inside.gratipay.com/certs/tmp/live/assets.gratipay.com/fullchain.pem.
   Your cert will expire on 2017-05-11. To obtain a new or tweaked
   version of this certificate in the future, simply run certbot
   again. To non-interactively renew *all* of your certificates, run
   "certbot renew"
 - If you like Certbot, please consider supporting our work by:

   Donating to ISRG / Let's Encrypt:   https://letsencrypt.org/donate
   Donating to EFF:                    https://eff.org/donate-le

[gratipay] $
```

**Comment by whit537** [comment]
screen shot 2017-02-10 at 7 15 21 pm

-------------------

screen shot 2017-02-10 at 7 15 43 pm

**Comment by whit537** [comment]
Alright! Now for the big one: `gratipay.com`. 👍

**Comment by whit537** [comment]
Suuuuuuure feel stupid copy/pasting all these strings. O.o

```
-------------------------------------------------------------------------------
Press Enter to Continue
Waiting for verification...
Cleaning up challenges
Failed authorization procedure. gittip.co (http-01): urn:acme:error:connection :: The server could not connect to the client to verify the domain :: DNS problem: SERVFAIL looking up A for gittip.co, www.gittip.co (http-01): urn:acme:error:connection :: The server could not connect to the client to verify the domain :: DNS problem: SERVFAIL looking up A for www.gittip.co

IMPORTANT NOTES:
 - If you lose your account credentials, you can recover through
   e-mails sent to support@gratipay.com.
 - The following errors were reported by the server:

   Domain: gittip.co
   Type:   connection
   Detail: DNS problem: SERVFAIL looking up A for gittip.co

   Domain: www.gittip.co
   Type:   connection
   Detail: DNS problem: SERVFAIL looking up A for www.gittip.co

   To fix these errors, please make sure that your domain name was
   entered correctly and the DNS A record(s) for that domain
   contain(s) the right IP address. Additionally, please check that
   your computer has a publicly routable IP address and that no
   firewalls are preventing the server from communicating with the
   client. If you're using the webroot plugin, you should also verify
   that you are serving files from the webroot path you provided.
 - Your account credentials have been saved in your Certbot
   configuration directory at
   /Users/whit537/personal/gratipay/inside.gratipay.com/certs/tmp. You
   should make a secure backup of this folder now. This configuration
   directory will also contain certificates and private keys obtained
   by Certbot so making regular backups of this folder is ideal.
[gratipay] $
```

**Comment by whit537** [comment]
I've added `gittip.co` in DNSimple.

**Comment by whit537** [comment]
Okay, made it! 💃 

I had to go through it several times, due to copy/paste errors. 😞  I think `certbot` was smart enough to only reverify the as-yet unverified domains, but it still presented new tokens for all twelve of them, and I re-entered all twelve each time. 😩

Okay! Let's get this installed at Heroku ...

```
-------------------------------------------------------------------------------
Press Enter to Continue
Waiting for verification...
Cleaning up challenges
Generating key (4096 bits): /Users/whit537/personal/gratipay/inside.gratipay.com/certs/tmp/keys/0000_key-certbot.pem
Creating CSR: /Users/whit537/personal/gratipay/inside.gratipay.com/certs/tmp/csr/0000_csr-certbot.pem
Non-standard path(s), might not work with crontab installed by your operating system package manager

IMPORTANT NOTES:
 - Congratulations! Your certificate and chain have been saved at
   /Users/whit537/personal/gratipay/inside.gratipay.com/certs/tmp/live/gittip.co/fullchain.pem.
   Your cert will expire on 2017-05-11. To obtain a new or tweaked
   version of this certificate in the future, simply run certbot
   again. To non-interactively renew *all* of your certificates, run
   "certbot renew"
 - If you like Certbot, please consider supporting our work by:

   Donating to ISRG / Let's Encrypt:   https://letsencrypt.org/donate
   Donating to EFF:                    https://eff.org/donate-le

[gratipay] $
```

**Comment by whit537** [comment]
```
$ heroku certs:add -a gratipay fullchain.pem privkey.pem --type sni
[...]
=== Your certificate has been added successfully.  Update your application's DNS settings as follows
Domain            Record Type  DNS Target
────────────────  ───────────  ──────────────────────────────
gittip.co         ALIAS/ANAME  gittip.co.herokudns.com
gratipay.com      ALIAS/ANAME  gratipay.com.herokudns.com
gratipay.org      ALIAS/ANAME  gratipay.org.herokudns.com
www.gittip.co     CNAME        www.gittip.co.herokudns.com
gratipay.net      ALIAS/ANAME  gratipay.net.herokudns.com
www.gittip.org    CNAME        www.gittip.org.herokudns.com
gratipay.co       ALIAS/ANAME  gratipay.co.herokudns.com
gittip.com        ALIAS/ANAME  gittip.com.herokudns.com
www.gratipay.com  CNAME        www.gratipay.com.herokudns.com
gittip.org        ALIAS/ANAME  gittip.org.herokudns.com
www.gratipay.co   CNAME        www.gratipay.co.herokudns.com
www.gittip.com    CNAME        www.gittip.com.herokudns.com
www.gratipay.net  CNAME        www.gratipay.net.herokudns.com
www.gratipay.org  CNAME        www.gratipay.org.herokudns.com
```

**Comment by whit537** [comment]
Blech, do we have to set a different CNAME/ALIAS for every single variant. 😶

Right now they are all CNAMEd to `gratipay.com`. I've update `gratipay.com`. Does that mean the rest of them are going to break?

**Comment by whit537** [comment]
Alright, I've updated them all in DNSimple. Now let's see about clearing my DNS cache so I can test ...

**Comment by whit537** [comment]
No luck clearing cache (tried some things and rebooted, even). However, variants that wouldn't be expected to be in my cache redirect cleanly, based on the IPs in a dig vs. gratipay.com. I think we're good? Will check later. We also need to [remove](https://devcenter.heroku.com/articles/ssl#remove-ssl-endpoint-add-on-after-24-hours) the old SSL endpoint (saves $20/mo!).

screen shot 2017-02-10 at 8 12 23 pm

```
$ dig gratipay.com

; <<>> DiG 9.8.3-P1 <<>> gratipay.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 1527
;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;gratipay.com.                  IN      A

;; ANSWER SECTION:
gratipay.com.           1607    IN      A       54.221.240.156
gratipay.com.           1607    IN      A       54.225.168.249
gratipay.com.           1607    IN      A       23.23.160.184

;; Query time: 5 msec
;; SERVER: 10.0.1.1#53(10.0.1.1)
;; WHEN: Fri Feb 10 20:15:17 2017
;; MSG SIZE  rcvd: 78

$
```

**Comment by whit537** [comment]
Almost there! 🐭

**Comment by whit537** [comment]
Green for you no, @clone1018? ☺️ 

screen shot 2017-02-11 at 2 09 15 am

**Comment by clone1018** [comment]
image

!m @whit537

**Comment by whit537** [comment]
Alright, I've dusted off and pushed the docs/ini files from last week's escapade. Look okay, @clone1018 et al.?

**Comment by whit537** [comment]
Merging because it's mostly docs and the config is already in use.

**Comment by whit537** [comment]
Also, I've removed the SSL Endpoint add-on at Heroku.

**Pull request merged**
