### PR TITLE
i18n for Big Picture

### LINKED ISSUE #132: Multilingual support for inside.gratipay.com
http://inside.gratipay.com does not seem to support multilingual (while https://gratipay.com does).
If this support could be added I would be happy to help for the French translation.

### PR DESCRIPTION
**Pull request by whit537**
Closes #132.

### CODE REVIEW

**Comment by whit537** [comment]
Blocked on #133.

**Comment by techtonik** [comment]
Unblocked. But.. The question is - how to keep the translations in sync? For the translator, it is kind of important to know both **coverage** (how many pages are there and how many are translated) and **outdated ratio** (how many revisions a certain translated certain page is behind the latest version).

**Comment by nashe** [comment]
Why not using Transifex, like the `gratipay` repository? You can create another "Resource" in their interface and give the URL of this repository, thereby Transifex will automatically download the files (each day? I'm not sure) and make them ready to be translated.

By the way @whit537, if you merge this PR, I will improve the French translation of the welcome page.

**Comment by whit537** [comment]
@nashe Merged! :-)

**Pull request merged**
