### PR TITLE
Allow only GET/HEAD/POST

### PR DESCRIPTION
**Pull request by nashe**
This aims to fix [H1-117142](https://hackerone.com/reports/117142).

Should we add tests for this?

### CODE REVIEW

**Comment by nashe** [comment]
(Writing the tests anyway since I never did this for aspen)

**Comment by whit537** [comment]
Yay tests! 💃

Since we already have a `.travis.yml` (we're using Travis for deployment), how about modifying it to actually run the tests now that we have some? :-)

**Comment by nashe** [comment]
Let's see if everything works before trying to add cache.

**Comment by whit537** [comment]
> Skipping a deployment with the heroku provider because the current build is a pull request.

https://travis-ci.org/gratipay/inside.gratipay.com/builds/145687885#L241

👍

**Comment by nashe** [comment]
```python
for allowed in ['GET', 'gEt', 'POST', 'HEAD']:
        response = client.hit('GET', trace='/')
```
Why ._____.

Fixing this.

**Comment by whit537** [comment]
?

**Comment by nashe** [comment]
I'm always doing 'GET' request in the test, but 4 times, rather than trying the different allowed methods. I'll fix it while introducing new tests in #788.

**Pull request merged**
