### PR TITLE
Change the social banner to match what is on site

### PR DESCRIPTION
**Pull request by whit537**
Any objections?

### CODE REVIEW

**Comment by rohitpaulk** [comment]
Should we update this on [Twitter](https://twitter.com/Gratipay/) too?

**Comment by whit537** [comment]
Well, yeah. If we're agreed that this is a good direction, we should update on all the social networks mentioned on http://inside.gratipay.com/big-picture/brand.

**Comment by whit537** [comment]
I guess since this is a "big picture" change, we have our first vote! cc: @clone1018 

> The following decisions require a vote with a seven day voting period and a majority in favor to pass:

http://inside.gratipay.com/big-picture/operating-agreement

**Comment by whit537** [comment]
That's seven days from when we call the vote, but it feels like we should have some discussion before calling the vote. Hmm ... we may want to tweak the operating agreement after going through this experience. ☺️

**Comment by mattbk** [comment]
Do you just need a motion and second?

**Comment by clone1018** [comment]
My impression is @whit537 is waiting to call the vote until discussion is finalized.

**Comment by whit537** [comment]
Oh heck ... I call the vote! Seven days starts now. ☺️

**Comment by whit537** [comment]
I vote in favor. @clone1018?

**Comment by clone1018** [comment]
I vote in favor.

**Comment by whit537** [comment]
Okay! Now we sit here like silly gooses for a week. 😊  :duck:

**Comment by whit537** [comment]
Twitter updated: https://twitter.com/Gratipay.

**Comment by whit537** [comment]
Google: https://plus.google.com/+Gratipay
Facebook: https://www.facebook.com/Gratipay

**Comment by whit537** [comment]
Instagram doesn't have a banner?

**Comment by whit537** [comment]
Medium: https://gratipay.news/

I made some other tweaks to our profile as well:

- linked our Twitter to the publication instead of the Gratipay account so the follower count is attached to the publication
- set favicon and publication logo
- added global `open source` tag

screen shot 2017-08-07 at 6 59 47 am

**Comment by whit537** [comment]
https://twitter.com/Gratipay/status/894517726366109696

**Pull request merged**
