### PR TITLE
Revise review howto in light of ToS changes

### PR DESCRIPTION
**Pull request by whit537**
Part of https://github.com/gratipay/inside.gratipay.com/issues/432.

Closes https://github.com/gratipay/inside.gratipay.com/issues/803.

### CODE REVIEW

**Comment by whit537** [comment]
Ready for review, @mattbk!

**Comment by whit537** [comment]
screen shot 2016-10-22 at 4 12 05 pm

**Comment by mattbk** [comment]
Should we have some sort of note in there about how we used to require open work, since it's discussed in the project-review repo?

Also, this has to wait for https://github.com/gratipay/gratipay.com/pull/4117 to merge, correct?

**Comment by whit537** [comment]
> since it's discussed in the project-review repo?

You mean in the `project-review` readme, or in tickets? If the former, let's take it [out](https://github.com/gratipay/team-review/pull/281); if the latter, do you really think we need to worry about it? Is the concern that someone might read an old ticket and wonder what we're talking about?

**Comment by whit537** [comment]
> Also, this has to wait for gratipay/gratipay.com#4117 to merge, correct?

Yeah, I think we should queue up all of these PRs, and then merge and deploy them as close together as we can.

**Comment by whit537** [comment]
> these PRs

Namely, the ones under todo on https://github.com/gratipay/inside.gratipay.com/issues/432.

**Comment by mattbk** [comment]
In tickets. The concern is that someone might read old tickets in order to understand whether their project fits in...well, never mind. We have new TOS that covers everything. If people are confused they can ask, or look at an old version of this page.

**Comment by whit537** [comment]
On the other hand, new folks who read the docs and see a note about the old way will _also_ be confused. In general I think it's better to let the past be in the past.

frozen-image-frozen-36220509-500-209

**Comment by mattbk** [comment]
No worries. At least _I_ know about it, so I can effectively support. ;)

**Comment by whit537** [comment]
Well, but this document is aimed at internal staff such as yourself. It's fair to add a line giving context for old review tickets.

**Comment by whit537** [comment]
Do we need to think about project review for npm packages (https://github.com/gratipay/gratipay.com/issues/4148) now? Or do we punt on that?

**Comment by whit537** [comment]
> Or do we punt on that?

Punt, I think.

**Comment by whit537** [comment]
In which case I am good to go here. How's it look to you, @mattbk et al.?

**Comment by mattbk** [comment]
Most recent changes LGTM.

**Pull request merged**
