### PR TITLE
bring back an onboarding doc

### PR DESCRIPTION
**Pull request by whit537**
We lost this in #498, but we need something like this. This new version is more general, details can get handled in the onboarding tickets.

### CODE REVIEW

**Comment by whit537** [comment]
@mattbk @techtonik et al. How's this look?

**Comment by whit537** [comment]
P.S. I want to include a link to this in a reply to https://twitter.com/BACHI_BS/status/704890285839482880.

**Comment by mattbk** [comment]
How does this relate to http://inside.gratipay.com/big-picture/welcome?

**Comment by whit537** [comment]
Good question. Lemme revise that here, too ...

**Comment by whit537** [comment]
Better in ae46886cf6a23819ca7938e95ddd57f263efdd59, @mattbk?

**Comment by mattbk** [comment]
I was originally confused about the relationship among the different Gratipay repositories. Is there a way to clarify that the inside.gratipay.com issue queue is management/onboarding as well as the IG website?

**Comment by whit537** [comment]
> I was originally confused about the relationship among the different Gratipay repositories. Is there a way to clarify that the inside.gratipay.com issue queue is management/onboarding as well as the IG website?

Yes, but that should be a separate PR/ticket. Eh?

**Comment by whit537** [comment]
I'm thinking in terms of a repo layout document similar to https://github.com/AspenWeb/salon/tree/4a6c0679ba541cc3ae34457db50dccff393936cb#contributing-to-aspen. You probably wanted a smaller mention here?

**Comment by whit537** [comment]
Not seeing where that would go here, got suggested wording?

**Comment by whit537** [comment]
Okay to merge, @mattbk?

**Comment by whit537** [comment]
Thanks! :-)

**Comment by whit537** [comment]
Followed up at https://twitter.com/Gratipay/status/705806809198628865.

**Pull request merged**
