### PR TITLE
Operating Agreement

### LINKED ISSUE #72: adopt a cooperative operating agreement
It's time. Gittip right now is an LLC that is wholly owned by me. Gittip is _de facto_ owned by the subset of our users that think of themselves as owning Gittip. We need to make this real _de jure_. I think we should be able to do this by writing ~~bylaws~~ _an operating agreement_ for the current LLC.

### PR DESCRIPTION
**Pull request by whit537**
Closes #72.

### Preview

https://gratipay-operating-agreement.herokuapp.com/big-picture/operating-agreement

### Todo

- [x] specify record-keeping
- [x] sort out {member,manager}-managed vis-a-vis active/passive membership
- [x] access
- [x] twyw
- [x] profit-sharing
- [x] minimize code changes required to put this into effect
  - [x] ~~figure out digital signatures~~ &hellip; punting, keeping it general in here for now
- [x] ~~have Janelle look it over?~~ &hellip; out of time, maybe later
- [x] members may not sell their membership
- [x] publicness?
- [x] revise the rest of the big picture &hellip; out of scope
- [x] something about no self-merging?
- [x] review vote thresholds
- [x] say something about capital contributions
  - [x] zero required
  - [x] but what about when we do?
- [x] figure out allowances and splitting expenses
- [ ] sort out capital allocations

### Deploy

- [ ] replace `CANONICAL_URL` with  `ASPEN_BASE_URL`

### CODE REVIEW

**Comment by whit537** [comment]
I'm looking at setting up a sandbox for easier real-time review.

**Comment by whit537** [comment]
I've got a new app created and I'm trying to get Travis to build and deploy to it. Currently:

> Skipping a deployment with the heroku provider because the current build is a pull request.

How do we get back to building twice?

**Comment by whit537** [comment]
Built twice ... did one deploy!?

**Comment by whit537** [comment]
Yes!

screen shot 2017-05-22 at 10 54 42 am

**Comment by whit537** [comment]
Getting weird behavior:

- restart app
- hit http://gratipay-operating-agreement.herokuapp.com/assets/inside-gratipay.svg, loads fine (repeat, fine)
- hit http://gratipay-operating-agreement.herokuapp.com/
- app crashes

**Comment by whit537** [comment]
Seeing `Process exited with 139`

**Comment by whit537** [comment]
Uuuuh ... [segfault](https://www.postgresql.org/message-id/Pine.LNX.4.21.0006241904051.348-100000@localhost.localdomain)!?

**Comment by whit537** [comment]
[Using Python 2.7.11](https://travis-ci.org/gratipay/inside.gratipay.com/builds/234854887#L289).

**Comment by whit537** [comment]
Yeesh. Lucked out on that one! Upgrading `libsass` seems to have worked.

cc: @dmk246 ;-)

**Comment by whit537** [comment]
Alright, preview is deployed:

https://gratipay-operating-agreement.herokuapp.com/big-picture/operating-agreement

**Comment by whit537** [comment]
Ping @clone1018 @rohitpaulk @mattbk et al. [Rough draft](https://gratipay-operating-agreement.herokuapp.com/big-picture/operating-agreement) is ready for initial review. Gonna let it sit a couple days and then revise. The one thing I still want to fold in from @clone1018's draft is the part about profit distribution in the case of dissolution.

**Comment by clone1018** [comment]
> For each system, Gratipay invites members to have access to the system by a vote of 100% of the subset of members who already have access to the system
Love it so far

**Comment by rohitpaulk** [comment]
> Gratipay makes guaranteed payments to its members on a weekly basis, using the same “take-what-you-want” (“twyw”) system by which it also distributes money to certain of its independent contractors.

Will we have people on the Gratipay team who aren't members of the co-operative? 

> At the end of Gratipay's fiscal year, which runs from June 1 through May 31, Gratipay's profits or losses are allocated to each member's capital account based on the amount of time they were a member during the preceding year. When Gratipay removes a member, the balance in their capital account is allocated to each remaining member's capital account in the same fashion. Gratipay retains all earnings. Gratipay does not distribute profits apart from guaranteed payments.

Does 'guaranteed payments' refer to the twyw payments? Is a capital account the one through which a member can draw gratipay-related expenses (the debit-card mentioned in the second paragraph)?

**Comment by rohitpaulk** [comment]
> The expense counts against their total monthly allowance in a ratio determined by consensus of the members involved. So, for example, payment of an invoice for $200 might be authorized by three members at 50%, 30%, and 20%, so that their available monthly allowance would decrease by $100, $60, and $40 respectively.

That... sounds like it'd be tricky. Can't we do equal splits, and the cases that require uneven splits can be considered as two different expenses? I might be missing cases where this would be required though.

**Comment by mattbk** [comment]
What's the difference between "profits" and "earnings"?

> Will we have people on the Gratipay team who aren't members of the co-operative?

That doesn't seem implied by 

> Gratipay maintains membership records on Gratipay.com [https://gratipay.com/Gratipay/distributing/].

> Any member with control over access to a subsystem may withdraw access from any other member at any time for any reason.

I assume this will be recorded in the onboarding ticket as a matter of course.

> Does 'guaranteed payments' refer to the twyw payments?

Yes (although if more than TWYW is added for other projects, will it be an option for the Gratipy project as well, or are we stuck on TWYW?):

> Gratipay makes guaranteed payments to its members on a weekly basis, using the same “take-what-you-want” (“twyw”) system by which it also distributes money to certain of its independent contractors.

> Members are entitled to a debit card,

Sounds like https://github.com/basecamp/handbook. :wink:

-----

The rest sounds pretty good, as far as it goes. I assume more rules may be needed as time goes on. Simple majority to change the operating agreement? Is an operating agreement the same as bylaws?

**Comment by whit537** [comment]
> Is an operating agreement the same as bylaws?

Yeah, basically. LLCs have operating agreements whereas C corps have bylaws.

**Comment by whit537** [comment]
> Will we have people on the Gratipay team who aren't members of the co-operative?

Yes, I was thinking the Gratipay team on Gratipay would encompass owners and contractors, as well as volunteers post-https://github.com/gratipay/gratipay.com/issues/4299.

**Comment by whit537** [comment]
> Does 'guaranteed payments' refer to the twyw payments?

Yeah, basically.

> Is a capital account the one through which a member can draw gratipay-related expenses (also, is that the account to which the debit-card mentioned in the second paragraph will be linked)?

No, the capital account is where profit accrues. Gratipay-related expenses come out of our checking account at PNC bank, via the debit cards mentioned.

> What's the difference between "profits" and "earnings"?

They're basically the same thing. The phrase "retained earnings" is a term of art in accounting, but yeah it basically means "retained profits" or "profits that you didn't distribute to members." One big wrinkle with LLCs as a structure is that even when profits/earnings are retained, they still count as income for individual members. So if there are four of us and we earn $10,000 in profit in a year, then each of us will have to report $2,500 extra income on our personal tax return to the IRS, even though the $2,500 is still "locked up" in the cooperative (that money isn't actually available to us personally). The reason we want to keep some money "locked up" in the cooperative is simply for cash flow. Apart from needing cash for daily operations, the cooperative ought to have cash on hand to handle emergencies and respond quickly to opportunities. I am anticipating that the amount we end up keeping on hand will be a subject of negotiation in our weekly takes, since weekly takes are the mechanism whereby each of us has access to the cooperative's money to pay ourselves (vs. access to pay vendors via the debit cards linked to our operating account at PNC).

Our weekly takes are "guaranteed payments," which means that even though they are technically distributions of profit (they are a "draw" against the profit that we'd otherwise receive at the end of the year when we settle up), they are distributed a) independently of income, and b) in view of work we perform as part of providing the cooperatives goods and services. They're a quasi-salary, in other words, for owners (vs. employees or contractors).

**Comment by whit537** [comment]
> if more than TWYW is added for other projects, will it be an option for the Gratipy project as well, or are we stuck on TWYW?

I hope we're not _stuck_ with anything. 😛 

That'd probably mean voting on an operating agreement change, though ...

> Simple majority to change the operating agreement?

Yeah, maybe. Noted in ticket todo as "review vote thresholds."

**Comment by whit537** [comment]
> That... sounds like it'd be tricky. Can't we do equal splits, and the cases that require uneven splits can be considered as two different expenses? I might be missing cases where this would be required though.

I'm looking for some kind of [co-budgeting](https://medium.com/@Cobudget/getting-started-with-collaborative-funding-265dabef30e3) here. I'm thinking about our recurring expenses as well as one-time things. I want us each to have the flexibility to sign up for new services, buy new domain names, go to conferences, etc. I want us to be able to spread the burden, so that, e.g., @clone1018 doesn't end up with _all_ of our Heroku cost against his allowance, even though it might be his card that ends up getting used for it. I want a way for someone to take initiative and purchase something, and for the rest of us to come along and say "Yeah, I agree with that decision" by sharing in the authorization of the expense.

**Comment by whit537** [comment]
Alright @clone1018 @rohitpaulk @mattbk et al., I've made a second draft of the operating agreement in 3ad3fa0c99f2bf1eb3e853477cc95bb1c50042a1, and I've spun up the staging dyno again so you can read it more easilier:

https://gratipay-operating-agreement.herokuapp.com/big-picture/operating-agreement 

The biggest change is in the Money section, which I overhauled to better specify how we allocate profits and losses. The tricky thing about LLCs is that profit/loss counts as income to each of us even if we keep it inside of Gratipay. If Gratipay has $20,000 in profit and we split that five ways, we'd each have to pay tax on an extra $4,000 of income even though we don't personally benefit from it. I think the fairest way to deal with that is to **allocate** profit/loss on the total twyw **distribution** amount. It puts downward pressure on the people who are taking the most, which I think is right.

> Can't we do equal splits, and the cases that require uneven splits can be considered as two different expenses?

I relaxed the language around this to say it's equal by default. S'okay?

I also fine-tuned the details of voting.

Let me know what you think!

**Comment by whit537** [comment]
Per [slack](https://gratipay.slackarchive.io/gratipay/page-100/ts-1497530406648026) we are aiming to work on this and hopefully land it tomorrow.

**Comment by rohitpaulk** [comment]
> I think the fairest way to deal with that is to allocate profit/loss on the total twyw distribution amount.

That makes sense to me.

**Comment by clone1018** [comment]
I've read through the new update and it all seems great to me.

**Comment by whit537** [comment]
[slack](https://gratipay.slackarchive.io/gratipay/page-100/ts-1497639760583153)

**Comment by whit537** [comment]
With +1s from @rohitpaulk and @clone1018 I am going to go ahead and self-merge this. I am the sole owner of Gratipay right now, so it is my prerogative to adopt an operating agreement. Once adopted, I will be the sole member of the co-op, and I can propose to invite new members! :-)

**Pull request merged**
