### PR TITLE
Add a Glossary

### LINKED ISSUE #243: Add Glossary page
From https://github.com/gratipay/inside.gratipay.com/issues/224#issuecomment-109052351

Probably on http://inside.gratipay.com/appendices/glossary to clarify what all buzzwords are about:
- ACH
- PCI
- CDD - https://github.com/gratipay/inside.gratipay.com/issues/219

This could be split into sections to indicate the value of these terms to GP. It should also include examples related to GP and links to where it is used. Pictures and visuals! There is a clear lack of those.

### PR DESCRIPTION
**Pull request by chadwhitacre**
Closes #243.

### CODE REVIEW

**Comment by techtonik** [comment]
LGTM.

**Comment by techtonik** [comment]
I would add some sections.

**Banking**

ACH (Automated Clearing House) - legacy system for transfers between accounts of different banks that works like the old way when all requests were passed on signed papers.

**Taxing**

Fiscal Sponsorship - ???

**Comment by techtonik** [comment]
**Finance**

MSB (Most Significant Bit, just joking) - Money Services Business, a type of company that is defined by ??? and regulated by FinCEN - https://www.fincen.gov/financial_institutions/msb/ Breaking FinCEN rules leads to ???

**Comment by techtonik** [comment]
**Banking**

BSA (Bank Secrecy Act) - a rule by FinCEN (US Government) that requires US banks to spy on their clients and report everything that can be classified as tax evasion and money laundering (correct me if I wrong).

**Comment by whit537** [comment]
P.S. We can remove https://github.com/gratipay/gratipay.com#glossary once this lands.

**Comment by whit537** [comment]
> LGTM.

What? There's nothing there yet! :flushed: 

> I would add some sections.

Then add some sections! You have access on this repo, yes? Push to the glossary branch!

**Pull request closed without merging**
