### PR TITLE
Update HackerOne policy

### PR DESCRIPTION
**Pull request by EdOverflow**
I have added a couple of rules to ensure quality reports.

### CODE REVIEW

**Comment by mattbk** [comment]
Looks good to me, although I'm not involved in the security program.

**Comment by whit537** [comment]
How are you with the commits I've made, @EdOverflow?

Also interested in @dmk246's opinion ...

**Comment by EdOverflow** [comment]
Thanks @whit537! I am happy with that.

**Comment by whit537** [comment]
@EdOverflow Cool. Let's give @dmk246 time to respond and then we can roll this out.

**Comment by dmk246** [comment]
Awesome! I love it!  Hoping this will help out !! 
Thanks for this!

**Comment by whit537** [comment]
Deployed: https://hackerone.com/gratipay.

**Pull request merged**
