### PR TITLE
Stop migrating tips

### PR DESCRIPTION
**Pull request by whit537**
Per https://github.com/gratipay/inside.gratipay.com/issues/536.

### CODE REVIEW

**Comment by whit537** [comment]
Ready for a landing, @clone1018 @rohitpaulk @mattbk et al.

**Comment by mattbk** [comment]
Looks pretty straightforward to me.

**Comment by whit537** [comment]
You know what to do! 💃

**Comment by whit537** [comment]
https://github.com/gratipay/gratipay.com/pull/4219 is in! This is next ...

**Comment by whit537** [comment]
💃

**Pull request merged**
