### PR TITLE
Replace misaka with mistune

### PR DESCRIPTION
**Pull request by techtonik**
This step makes it easier to run igp on Windows without additional Virtual Machine.

### CODE REVIEW

**Comment by whit537** [comment]
Build failure?

**Comment by techtonik** [comment]
@whit537 yes, old pip is unable to install stuff from vendor/ and wants to redownload it. Old virtualenv is unable to install wheels.

**Comment by techtonik** [comment]
@whit537 ready to be merged.

**Comment by whit537** [comment]
Over in [H1-84740](https://hackerone.com/reports/84740) we discovered a security configuration issue with misaka on Gratipay.com. Since we're not dealing with unvetted user input over here, we don't have the same security concern.

**Comment by techtonik** [comment]
@whit537 I checked both links with default settings for `mistune` - it is not vulnerable.

**Pull request merged**
