### PR TITLE
Removed bad link

### LINKED ISSUE #873: 404 Error on inside.gratipay.com
While falling into the rabbit hole that is inside.gratipay I found a bad link. 

The welcome page: http://inside.gratipay.com/big-picture/welcome has a bad link to payroll (under the staff Role). It currently leads to this: https://gratipay.com/~Gratipay/members/ which has a 404 error on Chrome and Firefox.

### PR DESCRIPTION
**Pull request by JessaWitzel**
I'm not sure what the correct link is, so I fixed it by removing the bad link. :) closes #873

### CODE REVIEW

**Comment by kaguillera** [comment]
!m @JessaWitzel

LGTM - Looks good to me

@whit537  merging 

🎉

**Comment by JessaWitzel** [comment]
Yay! I deserve 0 kudos for this but I'm so excited for my first PR!

**Comment by whit537** [comment]
@JessaWitzel Awesome! Kudos to you! 😄 💃

**Comment by whit537** [comment]
Hmm ... still [showing](http://inside.gratipay.com/big-picture/welcome) the old link. Did I break deployment under #871?

**Comment by whit537** [comment]
We deploy to Heroku via Travis, and the [merge build](https://travis-ci.org/gratipay/inside.gratipay.com/builds/172055353) for this PR failed. Heroku shows no deployment for 27 days. Hmm ...

**Comment by whit537** [comment]
401 body: "{\"id\":\"unauthorized\",\"error\":\"Invalid credentials provided.\"}" (wrong API key?)

**Comment by whit537** [comment]
```
brew install ruby
brew link ruby --overwrite
gem install travis
travis encrypt $(heroku auth:token) --add deploy.api_key
```

https://docs.travis-ci.com/user/deployment/heroku/

**Comment by whit537** [comment]
PR in #876 ...

**Pull request merged**
