### PR TITLE
rework Brand page around Ladder of Love

### LINKED ISSUE #430: define "love"
Our [mission](http://inside.gratipay.com/big-picture/mission) is to cultivate an economy of gratitude, generosity, and love.

@tshepang suggests at https://github.com/gratipay/inside.gratipay.com/issues/319#issuecomment-162344913 that "love" is "vague, and depends too much on context."

I've offered at https://github.com/gratipay/inside.gratipay.com/issues/319#issuecomment-162138787 that love, for Gratipay, is an "[interdependent](https://en.wikipedia.org/wiki/Interdependence) union of wills."

@mattbk links us at https://github.com/gratipay/inside.gratipay.com/issues/319#issuecomment-163368090 to another conversation about defining love in a financial/economic context.

This question seems to warrant its own thread.

### PR DESCRIPTION
**Pull request by whit537**
Closes #430 and contributes to #319.

The Ladder of Love is:

```
            ------               ___
           /      \ ___      ___/   \______
        --/-  ___  /    \/  /  /    /      \
       /     /           \__     //_        \
      /                     \   / ___       |
      |           ___       \/+--/         /
       \__           \       \            /
          \__                 |          /
         \     /____      /  /       |   /
          _____/         ___       \/  /\
               \__      /      /    |    |
                  \____/   \______/____/
                    | \____/       |
                    |     love     |
                    |--------------|
                    |              |
                    |   openness   |
                    |--------------|
                    |              |
                    | transparency |
                    |--------------|
                    |              |
                    |   consent    |
                    |--------------|
                    |              |
____________________|____safety____|___________________________________________________
```

That's meant to be a cloud. :-) :cloud: 

See http://inside.gratipay.com/big-picture/brand/ for current "Brand Values" text.

Here's the new text as of e612418cf3f516f3ab9492e213147e29bb819201:

> ##### Brand Values: Ladder of Love
>
Our core brand values are safety, consent, transparency, openness, and love. We see each as dependent on the prior value to form a "ladder of love":
>
 - **love**&mdash;freely serving one another
 - **openness**&mdash;sharing control with one another
 - **transparency**&mdash;sharing information with one another
 - **consent**&mdash;not acting on another without their permission
 - **safety**&mdash;physical and emotional security
>
We see **gratitude** and **generosity**, referenced in our [mission](/big-picture/mission), as the economic expression of love.
>
Gratipay has been called "**sweetly idealistic**" (Elizabeth Weiss, [The New Yorker](http://www.newyorker.com/online/blogs/currency/2014/02/can-we-crowdfund-a-creative-middle-class.html)) and it's been accused of "**unabashed optimism**" (@traverseda, [on GitHub](https://github.com/gratipay/gratipay.com/issues/1659#issuecomment-28245596)). Yes.

### CODE REVIEW

**Comment by whit537** [comment]
Here's the text in 5d0a3fa51bd49b96c3a239358b20a6bd68710954:

> ##### Ladder of Love
>
Our primary brand values are safety, consent, transparency, openness, and love. We see each as dependent on the prior value to form a "ladder of love":
>
 - **love**&mdash;interdependent fellowship with one another
 - **openness**&mdash;sharing control with one another
 - **transparency**&mdash;sharing information with one another
 - **consent**&mdash;not acting on an individual without their permission
 - **safety**&mdash;individual physical and emotional security
>
We see **gratitude** and **generosity**, referenced in our [mission](/big-picture/mission), as the economic expression of love.
>
Gratipay has been called "**sweetly idealistic**" (Elizabeth Weiss, [The New Yorker](http://www.newyorker.com/online/blogs/currency/2014/02/can-we-crowdfund-a-creative-middle-class.html)) and it's been accused of "**unabashed optimism**" (@traverseda, [on GitHub](https://github.com/gratipay/gratipay.com/issues/1659#issuecomment-28245596)). Yes.

screen shot 2015-12-10 at 10 41 17 am

**Comment by whit537** [comment]
You'll see that I tweaked the definition of love here from the "interdependent union of wills" of #319 and #430, to "**interdependent fellowship**." Why? I think that "fellowship" is a less technical-sounding term than "union of wills" that actually gets closer to what we want: "The companionship of individuals in a congenial atmosphere and on equal terms" ([Free Dictionary](http://www.thefreedictionary.com/fellowship)), or "A company of people that share the same interest or aim. A feeling of friendship, relatedness or connection between people" ([Wiktionary](https://en.wiktionary.org/wiki/fellowship)).

As to "interdependent," I like the word because a) it ties together the civilizational scale (cf. Marx's original usage) with the interpersonal scale (via [care ethics](http://www.iep.utm.edu/care-eth/)), and b) it points to a golden mean between the extremes of individualism and collectivism:

> Some people advocate freedom or independence as the ultimate good; others do the same with devotion to one's family, community, or society. Interdependence can be a common ground between these aspirations.

**Comment by whit537** [comment]
I added "with one another" to love, openness, and transparency, to contrast with the emphasis on the individual in consent and safety.

**Comment by whit537** [comment]
Here's how I see the previous values fitting into the ladder of love:

 - **honesty**—somewhere between **transparency** and **openness**
 - **kindness**—subsumed under **love**
 - **collaboration**—subsumed under **openness**
 - **openness**—included directly
 - **direct, interpersonal communication**—somewhere between **openness** and **love**
 - **discussion and deliberation**—somewhere between **openness** and **love**
 - **safety**—included directly
 - **consent**—included directly

**Comment by whit537** [comment]
The change in 52da8a650de6fb58b7cb52676f256b527ffc9324 to love as "freely serving one another" came from a conversation with a friend who has successfully used a corporate value of "service" to encode Aquinas' conception of love: "amare est velle alicui bonum" ([*ST* I-II.26.4 *corpus*](http://www.corpusthomisticum.org/sth2026.html#34663); [translation] (http://www.newadvent.org/summa/2026.htm#article4))—"To love is to will good for another." Aquinas, in turn, is quoting Aristotle: "ἔστω δὴ τὸ φιλεῖν τὸ βούλεσθαί τινι ἃ οἴεται ἀγαθά" ([*Rhetoric* II.4](http://www.perseus.tufts.edu/hopper/text?doc=Aristot.+Rh.+2.4&fromdoc=Perseus%3Atext%3A1999.01.0059); [translation](http://rhetoric.eserver.org/aristotle/rhet2-4.html))—"Now, let it be that to love is to will for someone that which you take to be good." Service emphasizes the completion of will in action. I don't passively *wish* good for the others I'm working alongside, I *intend* it—and, as I'm able, I follow through on my intention.

What are you trying to get done? How can I help you?

**Comment by whit537** [comment]
At first blush, [IEP's entry](http://www.iep.utm.edu/love/) is more relevant than [SEP's](http://plato.stanford.edu/entries/love/).

**Comment by whit537** [comment]
Another intriguing angle: bell hooks, [*Feminism is for Everybody*](http://www.amazon.com/Feminism-Is-Everybody-Passionate-Politics/dp/0896086283):

> A genuine feminist politics always brings us from bondage to freedom, from lovelessness to loving....There can be no love without justice.—from the chapter "To Love Again: The Heart of Feminism"

P.S. I learned about this from Shanley.

Also: [*All About Love*](http://www.amazon.com/All-About-Love-New-Visions/dp/0060959479).

**Comment by traverseda** [comment]
I'd, personally, be inclined to steer a bit away from feminist politics. Not necessarily because they're wrong, but because they tend to steer towards controversy. Controversy seems to be a big part of their branding strategy. Take a look at this article, [The ToxoPlasma Of Rage](http://slatestarcodex.com/2014/12/17/the-toxoplasma-of-rage/).

I'd coach the feminist ideals in language that isn't obviously feminist.

As an example, a quick google for "Shanley" has articles like [this](http://valleywag.gawker.com/the-shanley-show-was-the-whole-thing-an-elaborate-hoax-1681398966) near the top results, questioning whether Shanley is a parody of the more controversial aspects of the modern social justice movement.

It would be better just to stay away from directly referencing that memeplex. It transfers via controversy.

**Comment by whit537** [comment]
@traverseda! Long time, no see! :-)

Yeah, Gittip/Gratipay has had its share of feminist-related controversy (see #319 ff.), which makes the connection all the more intriguing to me. I don't envision surfacing feminism by name on the Brand page, but I am intrigued to see what hooks herself has to say about love. My hunch is that there's convergence to be found.

**Comment by traverseda** [comment]
I am pretty familiar with the gittip incident.

My hunch is that there isn't a convergence, but good luck.

There's a difference between how a movement *presents* itself, and how it *behaves*. Look at concepts like "motte and bailey doctrine".

I'd also recommend not trying to service that market directly. As was demonstrated by the whole gittip thing, they have some very specific requirements. A lot of those requirements go counter to what I'd consider to make a good product. The site was significantly more usable, in my opinion, before that incident.

Thankfully, everything is open source. So it's not hard to make competing products to serve specific requirements. You can't please everyone.

Anyway, just my two cents. Don't try to specifically converge with communities that go on regular witch hunts or are otherwise fueled by controversy, instead just focus on making the best, kindest, project you can.

**Comment by kaguillera** [comment]
> Yeah, Gittip/Gratipay has had its share of feminist-related controversy (see #319 ff.), which makes the connection all the more intriguing to me.

:point_right: :bear:

**Comment by whit537** [comment]
> :point_right: :bear:

lol

(For context: @kaguillera and I co-work together, usually a couple times a week, and, in person, offline, he acts as a force for non-bear-poking within Gratipay—counterbalancing yours truly.)

**Comment by whit537** [comment]
Love: something we can all agree on! :-)

beck-love

fruit

**Comment by whit537** [comment]
I'm getting closer to landing this.

**Comment by whit537** [comment]
Bringing over @tshepang's -1 from https://github.com/gratipay/inside.gratipay.com/issues/107:

> I feel like we would lose nothing if we stop using the word *love* in our marketing material. Does anyone feel the same? The word is ambigous... what does love mean in the use of Gratipay? To me, admiring someone does not imply that I love them, as in the way I would love a friend, a romantic partner, or a descendant. I guess there are other kinds of love, but it's such an overused word that I feel it should be avoided if possible, unless we agree on exactly on what it means, and Gratipay should not be the place to provide such an explanation. Let's choose more precise words, like *admire* or *enjoy*.
>
Following is an example from [About](https://gratipay.com/about):
>
>> Gratipay (formerly Gittip) is a way to make small weekly cash payments to people you love and teams you respect.
>
That line feels like it would be at least as effective (and less mushy) if it was:
>
>> Gratipay (formerly Gittip) is a way to make small weekly cash payments to people and teams you respect.
>
I see *love* is used a lot in [the Mission](http://inside.gratipay.com/big-picture/mission) Explanation, with things like *Economy of love*. Am sure better words exist, like *Economy of kindness*, for example. Maybe even talk about a job you *enjoy* instead of one you *love*?
>
Anyways, the Mission itself could be something like:
>
>> Our mission is to enable an economy of gratitude and generosity.
>
I don't see that as less effective than:
>
>> Our mission is to enable an economy of gratitude, generosity, and love.
>
----
>
So, this word is:
>
* too ambiguous
* too mushy, which can be off-putting

**Comment by whit537** [comment]
I see mushiness as part of the Gratipay brand, to be honest—we are "sweetly idealistic," full of "unabashed optimism." And I agree that the word *love* is ambiguous, but I see this as a strength. What other word could suggest a possible point of convergence—however faint and tenuous—for personalities as disparate as Glenn Beck and bell hooks? Wow!

**Comment by whit537** [comment]
> I feel like we would lose nothing if we stop using the word *love* in our marketing material.

We might perhaps draw a distinction between marketing materials and internal materials, though of course those boundaries are blurred for us. Still, the mission page on Inside Gratipay is addressed to a different audience than our About page. I don't know if this is a practical distinction to employ, but it seems like it might be helpful?

**Comment by whit537** [comment]
> Still, the mission page on Inside Gratipay is addressed to a different audience than our About page.

Namely, collaborators instead of users.

**Comment by whit537** [comment]
Rebased on `master` at 260c459d72da56ab9ba8c49110732630d91bebac. Previous head was e612418cf3f516f3ab9492e213147e29bb819201.

**Comment by whit537** [comment]
Last call ...

**Comment by whit537** [comment]
Rebased on master. Previous head was 83f4e91f33d4ea95696ba2ff534a224658c87a11.

**Pull request merged**
