### PR TITLE
Revise the Big Picture

### PR DESCRIPTION
**Pull request by chadwhitacre**
The first half is actually pretty good still. Strategy is basically okay but wants some more detail. Customers should change. Not sure about org chart, but roadmap deserves better.

### CODE REVIEW

**Comment by whit537** [comment]
Making some good progress on strategy, but I think this work on estimating the market size of open source belongs in a blog post (referencing Sustain, #920) that we can link to from here and promote independently.

**Comment by whit537** [comment]
Draft blog post: https://gratipay.news/open-source-is-leaving-853b-on-the-table-9015eb7e293e

**Comment by whit537** [comment]
Gonna use these to estimate size of current value capture:

http://flossfoundations.org/foundation-directory
https://en.wikipedia.org/wiki/List_of_free_and_open-source_software_organizations

**Comment by whit537** [comment]
Actually, https://en.wikipedia.org/wiki/List_of_free_and_open-source_software_organizations links to other Wikipedia pages so it's hard to get links to the orgs themselves. Anyway the total capture is going to be negligible compared to the creation ... right? Let's do a quick estimation based on http://flossfoundations.org/foundation-directory and do a more thorough estimation if my expectation is way off base ...

**Comment by whit537** [comment]
Sad. Starting with OSI (first on list). Hard time finding a clear answer.

Oops. Not first on list but summing "[major contributions 2016](https://opensource.org/minutes20170111)" yields 173,517.

**Comment by whit537** [comment]
Draft drafted: https://gratipay.news/open-source-captures-0-08-of-the-value-it-creates-leaving-852b-on-the-table-9015eb7e293e.

**Comment by mattbk** [comment]
I like the draft, although I'm sure people can quibble about numbers (glad you linked to the spreadsheet).

Wish the call to action could be stronger:
> Our goal at Gratipay is to help the open source community capture more of the value it creates, by making it both socially and technically easy for companies to pay for open source. Want your company to be part of the solution? Drop me a line in email or Slack.

This is what we are working on:

> making it both socially and technically easy for companies to pay for open source

Is that enough description to be useful, or is more detail needed? I just think people could skim this and say "yeah, yeah, we just need to put more money in," which is decidedly _not_ the goal.

I looked around for a clear explanation on IG or Medium but didn't find one.

**Comment by whit537** [comment]
@mattbk I added links to the recent npm/package.json posts as examples. S'good?

I also took out Mozilla's search revenue ($500M/y down to 12) and did a little more clean up.

https://gratipay.news/open-source-captures-0-02-of-the-value-it-creates-leaving-852b-y-on-the-table-9015eb7e293e

I think I'm ready to go with this post. Any objections?

**Comment by whit537** [comment]
+1 from @mattbk in [slack](https://gratipay.slackarchive.io/gratipay/page-100/ts-1502100977285922) (scroll down? 😞 ).

Posted https://twitter.com/Gratipay/status/894959004270686208.

**Comment by whit537** [comment]
There are [20M](https://www.google.com/search?q=number+of+programmers+in+the+world) programmers in the world, so each would need a budget of $46,650/y to compensate the open source community for 100% of the value it creates.

**Comment by whit537** [comment]
If each has a budget of $1,200, that's $24B/y for open source.

**Comment by whit537** [comment]
Red Hat had revenues of $2B last year. To match that we need 2M programmers with $1k/y.

**Comment by whit537** [comment]
Another draft, for later I think: [Dear Joel: How about a 13th test?](https://gratipay.news/deal-joel-how-about-a-13th-test-d2ca0346c590).

**Comment by whit537** [comment]
I think we would want to have https://github.com/gratipay/gratipay.com/issues/1153 in place before publishing that.

**Comment by whit537** [comment]
I'm 30% into a customers rewrite and then I look forward to getting to roadmap. Basically:

1. give to package.json, w/ pledging
1. open source perks

But perhaps we can flesh that out further?

**Comment by whit537** [comment]
Alright, actually I'm not going to really touch the org chart and roadmap. 😊

On the other hand, I added 9e6af7ea7ef9e5bec58be87dff9950c471146f68 about voting timelines reflecting our experience in #1123.

Ready for review, @Gratipay!

**Comment by whit537** [comment]
Rebased, was 9e6af7ea7ef9e5bec58be87dff9950c471146f68. Deployed to:

https://inside-gratipay-com-staging.herokuapp.com/

**Comment by whit537** [comment]
Main changes to look for:

- redefines primary customer from `~picard` (open source project owner/maintainer) to `~alice` (tech company open source program director)
- rework Strategy around tragedy of the commons and put some numbers to it
- tweaks voting timelines in operating agreement

The rest are more cosmetic/stylistic.

**Comment by whit537** [comment]
@clone1018 Can I get you to look at this? We actually need to vote since it affects big picture docs.

**Comment by whit537** [comment]
Rebased, was b87bfdee3e8387925457fb54711b8fb9595c780a.

**Comment by whit537** [comment]
Want to do another commit on this working in [Ostrom](https://en.wikipedia.org/wiki/Elinor_Ostrom#Design_principles_for_Common_Pool_Resource_.28CPR.29_institutions) as part of https://github.com/gratipay/inside.gratipay.com/issues/1160#issuecomment-329603695.

**Comment by clone1018** [comment]
https://inside-gratipay-com-staging.herokuapp.com/big-picture/customers 👍 
https://inside-gratipay-com-staging.herokuapp.com/big-picture/mission 👍 
https://inside-gratipay-com-staging.herokuapp.com/big-picture/operating-agreement 👍 
https://inside-gratipay-com-staging.herokuapp.com/big-picture/strategy 👍 

All of these changes look good to me, my only comment was:

> Do you think referencing values like $1T/yr devalues them? $1T/yr vs $1,000,000,000,000/yr 
> Whenever I see you write like that I don't immediately understand the scale of it until I actually think about it

**Comment by whit537** [comment]
I think the consensus in [slack](https://gratipay.slackarchive.io/gratipay/) is to leave as-is?

**Comment by clone1018** [comment]
Yes I think so, let's worry about building a business that provides $1M/yr to open source :)

**Pull request closed without merging**
