### PR TITLE
Use peep to install packages

### PR DESCRIPTION
**Pull request by patcon**
Peep wraps pip and adds cryptographic hashes to ensure that packages don't change, even though pypi allows maintainers to remove and add package versions. I feel this might possibly be a better solution than version-controlling compressed tarballs, which I haven't personally come across outside python.

We need to use a fork of peep until this gets merged:
https://github.com/erikrose/peep/pull/29

cc: @seanlinsley

### CODE REVIEW

**Comment by mattbk** [comment]
Two years on, pinging to finish or close.

**Comment by whit537** [comment]
Cryptographic hashes are supported directly in pip now:

https://pip.pypa.io/en/stable/reference/pip_hash/

**Comment by whit537** [comment]
Closing. Besides the peep/pip drift, I don't feel a need to remove vendoring on IG at the moment.

**Comment by whit537** [comment]
Also, threat is low on IG. More important would be to `pip hash` on gratipay.com (are.

**Comment by erikrose** [comment]
Peep is derecated anyway. It's functionality has been merged into pip 8, so use that if you're going to do anything.

**Pull request closed without merging**
