### PR TITLE
Update heroku api key

### PR DESCRIPTION
**Pull request by whit537**
Look okay, @kaguillera @rohitpaulk @aandis @JessaWitzel et al.?

### CODE REVIEW

**Comment by whit537** [comment]
This fixes https://github.com/gratipay/inside.gratipay.com/pull/874#issuecomment-257395360.

**Comment by kaguillera** [comment]
Like simple enough to me.

**Comment by whit537** [comment]
Thanks, @kaguillera—looks like that worked!

@JessaWitzel You have code in production on http://inside.gratipay.com/big-picture/welcome! 💃

**Comment by whit537** [comment]
P.S. @kaguillera Don't forget to delete the branch after you merge a PR. Looks like @rohitpaulk picked that up this time. ;-)

**Comment by kaguillera** [comment]
cool, will do next time.

**Pull request merged**
