### PR TITLE
Keep up with radar and queue changes

### PR DESCRIPTION
**Pull request by chadwhitacre**
Now that we have chat again (#913), we should retire the radar tickets here in GitHub, since those were invented to do the thing that chat is for. While we're at it we should clean up our queue docs since those are also now out of date and closely related to the radar.

- [ ] fold https://github.com/gratipay/inside.gratipay.com/issues/923 into IG

### CODE REVIEW

**Comment by whit537** [comment]
HackerOne has severity ratings now, so we can set those there. Can we also add counts to http://inside.gratipay.com/appendices/disclosures?

**Comment by whit537** [comment]
The use:

`none`, `low`, `medium`, `high`, `critical` 

Which maps easily to our risk ratings:

`none`, `theoretical`, `mild`, `moderate`, `severe`

**Comment by whit537** [comment]
@dmk246 I have a project for you! :-) Would you be willing to go through our lists of [closed](http://inside.gratipay.com/appendices/disclosures) and [still-open](https://github.com/gratipay/inside.gratipay.com/issues/923) H1 tickets, and set a severity rating for each one? The field is on the upper right when you bring up a ticket, and it looks like this:

screen shot 2016-11-29 at 10 59 01 am

We just need to click "Add" and select a rating for each one of our tickets. Here's how our labels
(which are defined in our [program](http://hackerone.com/gratipay)) map to theirs:

| Ours ("risk") | Theirs ("severity") |
|--------|--------|
| n/a | `No Rating` |
| `none` | `None` |
| `theoretical` | `Low` |
| `mild` | `Medium` |
| `moderate` | `High` |
| `severe` | `Critical` |

In the future, every new ticket should get a rating (we'll work on that later :). The task right now is to backfill that field for all previous tickets—we've already categorized them ourselves, we just to record the info in HackerOne. Here are the lists of tickets with our categorizations:

- [finished tickets](http://inside.gratipay.com/appendices/disclosures)
- [open tickets](https://github.com/gratipay/inside.gratipay.com/issues/923)

Make sense? Up for it? :-)

**Comment by whit537** [comment]
@dmk246 Note that we don't need to do the CVSS scoring right now, just the simple five-point scale. It does say "or". ;-)

-------------------

screen shot 2016-11-29 at 11 21 26 am

**Comment by whit537** [comment]
I've emailed H1 about getting an API key so we can update the disclosures page to use the new severity ratings. Those are only available in [the API proper](https://api.hackerone.com/docs/v1). Turns out we've been using [a public API](https://hackerone.com/gratipay/reports/public) so far.

**Comment by dmk246** [comment]
@whit537 sorry for the delay been working on a few things.  I am up for it ....let me review your comments....(note I may have questions) ... thanks!

**Comment by whit537** [comment]
What delay? :)

**Comment by whit537** [comment]
Ftr @dmk246 and I were able to talk through this in person. 👍

**Comment by dmk246** [comment]
@whit537 where was the link to the tickets that need altered that we looked at yesterday ? I have looked everywhere that I can think .. but obviously I haven't seemed to find it... Sorry and Thanks

**Comment by whit537** [comment]
@dmk246 Here you go! Are these the right ones? :-)

- [finished tickets](http://inside.gratipay.com/appendices/disclosures)
- [open tickets](https://github.com/gratipay/inside.gratipay.com/issues/923)

**Comment by dmk246** [comment]
Thanks @whit537 Exactly!!

**Comment by dmk246** [comment]
These are done!  Note, under open tickets, https://hackerone.com/reports/143139 was listed as a theoretical risk, aka low risk, but @whit537 had set it to high risk on Nov. 29th ... just wanted to make you aware of this, so in case you needed to change  it in other locations.   :)

**Comment by whit537** [comment]
Awesome, thanks @dmk246! I'll proceed with the updates to the disclosures page now that we have all the tickets categorized ... and I'll take a look at that high/moderate one!

**Comment by whit537** [comment]
Okay, I made some progress on this. Hopefully I can make a commit soon!

**Comment by whit537** [comment]
I turned off the radar rotation in @gratipay-bot in https://github.com/gratipay/bot/commit/000283718329cd117ec9b9fdef32c11ff26e9769 and https://github.com/gratipay/bot/commit/c4cba995933cc65ff10d1b8b5e08e9c4ed9e16de.

**Pull request closed without merging**
